# Default values for frontend
replicaCount: 1
namespace: mb

image:
  repository: 898060563170.dkr.ecr.ap-south-1.amazonaws.com/mb-frontend
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

# Application specific configuration
config:
  environment: "production"
  apiBaseUrl: "http://dealservice:8080"
