apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mockservice.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mockservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mockservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mockservice.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        role: mbotr
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.config.profiles.active | quote }}
            - name: JAVA_OPTS
              value: {{ .Values.config.javaOpts | quote }}
